integrated eeg dataset for TUH
robustness-gym/meerkat pull request #153
Opened 2021-08-29 21:42 UTC by khaledsaab

2021-08-29 23:44 UTC, seyuboglu commented
Thanks for adding this! Instead of including all the files in the meerkat repo, can we provide a function that just downloads it from https://www.isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml? This way average meerkat users won't have to download these files when cloning. We could do something similar to `meerkat.contrib.imagenette.download_imagenette`

2021-08-29 23:44 UTC, krandiash commented
I was just literally about to comment this @seyuboglu

2021-08-29 23:57 UTC, khaledsaab commented
Great suggestion. I'll work on that and push the updates

2021-08-30 17:15 UTC, seyuboglu requested changes
A couple of nits, but otherwise lgtm once we remove the data files

2021-08-30 17:15 UTC, seyuboglu commented on meerkat/contrib/eeg/data_utils.py
> +def getSeizureTimes(file_name):
nit: snake case for functions

2021-09-03 17:22 UTC, khaledsaab commented
In the latest commit, I've removed unnecessary aux files and integrated necessary code to produce them if a meerkat user is interested in EEG. I also provided code and instructions for a meerkat user to download the EEG dataset, and do the necessary preprocessing steps. I'll be available to work through any bugs/errors that arise.

2021-09-03 18:17 UTC, krandiash commented
Looks great, thanks!

2021-09-03 18:17 UTC, merged